token: 'YOUR_BOT_TOKEN'
input_csv: '/PATH/TO/YOUR/INPUT/INPUT.CSV'
db_name: 'NAME_FOR_DB_TO_BE_GENERATED'
db_username: 'MYSQL_USER_NAME'
db_password: 'MYSQL_PASSWORD'
db_host: 'localhost'
db_port: 3306
